package leetcode.editor.cn;

//
//Given two strings s and t which consist of only lowercase letters. 
//
// String t is generated by random shuffling string s and then add one more lett
//er at a random position. 
//
// Find the letter that was added in t. 
//
// Example:
// 
//Input:
//s = "abcd"
//t = "abcde"
//
//Output:
//e
//
//Explanation:
//'e' is the letter that was added.
// Related Topics 位运算 哈希表 
// 👍 151 👎 0


/**
 * @author zoro-learner
 * @create 2020-09-02 16:50:47
 */
public class FindTheDifference {
    public static void main(String[] args) {
        Solution solution = new FindTheDifference().new Solution();
        
    }
    
//leetcode submit region begin(Prohibit modification and deletion)
class Solution {
    public char findTheDifference(String s, String t) {
        char res = 0;
        for (char ch : s.toCharArray()) {
            res ^= ch;
        }
        for (char ch : t.toCharArray()) {
            res ^= ch;
        }
        return res;
    }
}
//leetcode submit region end(Prohibit modification and deletion)

    
}